server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_NATIVE_SEARCH_LOCATION:file:../shared-config,classpath:/config}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
